### ISSUE TITLE
크로스 컴파일러 설치 문제

### ISSUE THREAD

**Issue by DarbySung** [guileschool/BEAGLEBONE-tutorials#1]
튜토리얼의 크로스 컴파일러 설치 부분에서 문제가 있어서 질문 드립니다.

크로스 컴파일러 설치, 경로 지정 끝난 뒤에

arm-none-eabi-gcc -v 를 실행하면
/usr/local/arm-2011.03/bin/arm-none-eabi-gcc: No such file or directort 라고 나옵니다.

하지만 ls를 이용해서 보면 컴파일러 목록은 정상적으로 보입니다.
우분투 버전 때문인가 싶어서 12.04로 다시 설치하고 작업해도 똑같습니다.
같이 공부하는 친구도 같은 증상이 나옵니다.

설치가 제대로 안된건가요? 추가적으로 작업해야하는게 있나요?

**Comment by guileschool** [comment]
영상확인하시구요(time 29:00 ~ 31:00)  https://www.youtube.com/watch?v=RZcrx9w33D8#t=29m00s
~/.bashrc 파일 수정하시고 터미널을 닫고 다시 열어서 확인해 보세요
eg. $which arm-none-eabi-gcc <엔터>
혹은
eg. $/usr/local/arm-2011.03/bin/arm-none-eabi-gcc <엔터>

**Comment by DarbySung** [comment]
![compiler_issue](https://cloud.githubusercontent.com/assets/17796537/18125701/a016bf02-6fb2-11e6-94a4-42cd4c92dbb3.PNG)

~/.bashrc 파일을 서브라임텍스트에서 수정하면 안되나요?
위 사진의 왼쪽 창처럼 수정하고 저장한 뒤
새로운 터미널을 열어서 오른쪽 창처럼 명령어를 치면 경로나 파일이 없다고 나옵니다.

**Comment by guileschool** [comment]
혹시 64비트 리눅스 환경이신가요? 
$ file /usr/local/arm-2011.03/bin/arm-none-eabi-gcc

만약 그렇다면 이 글이 도움이 될 듯 싶습니다. http://askubuntu.com/questions/133389/no-such-file-or-directory-but-the-file-exists

**Comment by DarbySung** [comment]
네 확인하고 해보도록 하겠습니다.

혹시 64bit PC에 32bit 우분투를 설치해서 사용해도 상관 없을까요?
이런 문제들이 종종 있을 것 같아서 32bit 환경이 나을까 싶어서요

**Comment by guileschool** [comment]
네, 설치 가능합니다. 해보시고 안되시면 다시 글 남겨주세요

**Comment by DarbySung** [comment]
32bit 우분투 설치하고 해결되었습니다!
